name: "Package version tests"
on: [workflow_dispatch, pull_request]

jobs:
  package-version-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: # Includes one more job
          - dir: 'BlockBlobReader/target/consumer_build'
          - dir: 'BlockBlobReader/target/dlqprocessor_build'
          - dir: 'BlockBlobReader/target/producer_build'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - working-directory: ${{ matrix.dir }}
        run: |
          set +e
          npm outdated >> output.txt
          cat output.txt
          cat output.txt | grep -v "Package" |  awk '$3!=$4' | wc -l |  awk  '{if ($1!=0) {print $1 " Deprecated packages found";} else {print "No Deprecated packages found";} }'